Feature 27
elenapantsurkina/Marketplace pull request #6
Opened 2024-11-18 14:09 UTC by elenapantsurkina

homework_27

2024-11-18 16:07 UTC, painassasin requested changes

2024-11-18 16:07 UTC, painassasin commented on users/forms.py
> +        fields = ("username", "email", "password1", "password2")
Поле username не нужно указывать при регистрации

Тебе это поле нужно удалить вообще из модели указав `username=None`

2024-11-18 16:07 UTC, painassasin commented on users/urls.py
> +    path("login/", LogoutView.as_view(), name="logout"),
Оба эндпоинта по адресу `login`

2024-11-19 03:21 UTC, elenapantsurkina commented on users/urls.py
> +    path("login/", LogoutView.as_view(), name="logout"),
исправила

2024-11-19 03:21 UTC, elenapantsurkina commented on users/forms.py
> +        fields = ("username", "email", "password1", "password2")
исправила

2024-11-19 13:39 UTC, painassasin approved these changes

2024-11-20 01:37 UTC, merged